/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgendarRouteImport } from './routes/_authenticated/agendar'
import { Route as AuthenticatedCentrosRouteImport } from './routes/_authenticated/centros'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedHospitalRouteImport } from './routes/_authenticated/hospital'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAgendamentosRouteImport } from './routes/_authenticated/admin/agendamentos'
import { Route as AuthenticatedAdminCampanhasRouteImport } from './routes/_authenticated/admin/campanhas'
import { Route as AuthenticatedAdminDoadoresRouteImport } from './routes/_authenticated/admin/doadores'
import { Route as AuthenticatedAdminEstoqueRouteImport } from './routes/_authenticated/admin/estoque'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendarRoute = AuthenticatedAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentrosRoute = AuthenticatedCentrosRouteImport.update({
  id: '/centros',
  path: '/centros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHospitalRoute = AuthenticatedHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAgendamentosRoute =
  AuthenticatedAdminAgendamentosRouteImport.update({
    id: '/admin/agendamentos',
    path: '/admin/agendamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCampanhasRoute =
  AuthenticatedAdminCampanhasRouteImport.update({
    id: '/admin/campanhas',
    path: '/admin/campanhas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDoadoresRoute =
  AuthenticatedAdminDoadoresRouteImport.update({
    id: '/admin/doadores',
    path: '/admin/doadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEstoqueRoute =
  AuthenticatedAdminEstoqueRouteImport.update({
    id: '/admin/estoque',
    path: '/admin/estoque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/admin/pedidos',
    path: '/admin/pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/centros': typeof AuthenticatedCentrosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/hospital': typeof AuthenticatedHospitalRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/agendamentos': typeof AuthenticatedAdminAgendamentosRoute
  '/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/admin/doadores': typeof AuthenticatedAdminDoadoresRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/centros': typeof AuthenticatedCentrosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/hospital': typeof AuthenticatedHospitalRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/agendamentos': typeof AuthenticatedAdminAgendamentosRoute
  '/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/admin/doadores': typeof AuthenticatedAdminDoadoresRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agendar': typeof AuthenticatedAgendarRoute
  '/_authenticated/centros': typeof AuthenticatedCentrosRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/hospital': typeof AuthenticatedHospitalRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/admin/agendamentos': typeof AuthenticatedAdminAgendamentosRoute
  '/_authenticated/admin/campanhas': typeof AuthenticatedAdminCampanhasRoute
  '/_authenticated/admin/doadores': typeof AuthenticatedAdminDoadoresRoute
  '/_authenticated/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agendar'
    | '/centros'
    | '/historico'
    | '/hospital'
    | '/painel'
    | '/perfil'
    | '/admin/agendamentos'
    | '/admin/campanhas'
    | '/admin/doadores'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agendar'
    | '/centros'
    | '/historico'
    | '/hospital'
    | '/painel'
    | '/perfil'
    | '/admin/agendamentos'
    | '/admin/campanhas'
    | '/admin/doadores'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agendar'
    | '/_authenticated/centros'
    | '/_authenticated/historico'
    | '/_authenticated/hospital'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/admin/agendamentos'
    | '/_authenticated/admin/campanhas'
    | '/_authenticated/admin/doadores'
    | '/_authenticated/admin/estoque'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agendar': {
      id: '/_authenticated/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AuthenticatedAgendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros': {
      id: '/_authenticated/centros'
      path: '/centros'
      fullPath: '/centros'
      preLoaderRoute: typeof AuthenticatedCentrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospital': {
      id: '/_authenticated/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof AuthenticatedHospitalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/agendamentos': {
      id: '/_authenticated/admin/agendamentos'
      path: '/admin/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AuthenticatedAdminAgendamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/campanhas': {
      id: '/_authenticated/admin/campanhas'
      path: '/admin/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AuthenticatedAdminCampanhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/doadores': {
      id: '/_authenticated/admin/doadores'
      path: '/admin/doadores'
      fullPath: '/admin/doadores'
      preLoaderRoute: typeof AuthenticatedAdminDoadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/estoque': {
      id: '/_authenticated/admin/estoque'
      path: '/admin/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AuthenticatedAdminEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendarRoute: typeof AuthenticatedAgendarRoute
  AuthenticatedCentrosRoute: typeof AuthenticatedCentrosRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedHospitalRoute: typeof AuthenticatedHospitalRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedAdminAgendamentosRoute: typeof AuthenticatedAdminAgendamentosRoute
  AuthenticatedAdminCampanhasRoute: typeof AuthenticatedAdminCampanhasRoute
  AuthenticatedAdminDoadoresRoute: typeof AuthenticatedAdminDoadoresRoute
  AuthenticatedAdminEstoqueRoute: typeof AuthenticatedAdminEstoqueRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendarRoute: AuthenticatedAgendarRoute,
  AuthenticatedCentrosRoute: AuthenticatedCentrosRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedHospitalRoute: AuthenticatedHospitalRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedAdminAgendamentosRoute: AuthenticatedAdminAgendamentosRoute,
  AuthenticatedAdminCampanhasRoute: AuthenticatedAdminCampanhasRoute,
  AuthenticatedAdminDoadoresRoute: AuthenticatedAdminDoadoresRoute,
  AuthenticatedAdminEstoqueRoute: AuthenticatedAdminEstoqueRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
